"""
Render results/SUMMARY.md from the calibration outputs.

Text is generated from the actual numbers rather than hand-written, so the write-up
cannot drift from the results it describes. Verdicts (collapse test, AOP ordering,
saturation) are computed, not asserted.
"""

import numpy as np


def _fmt(x, dp=0):
    if x is None or not np.isfinite(x):
        return "n/a"
    return f"{x:,.{dp}f}"


def _band(df, cell, col="C_ly50_abs", km_subset=None):
    s = df[df["cell_line"] == cell]
    if km_subset is not None:
        s = s[s["K_m"].isin(km_subset)]
    if s.empty:
        return None, None, None
    v = s[col].to_numpy(dtype=float)
    v = v[np.isfinite(v)]
    if v.size == 0:
        return None, None, None
    return float(v.min()), float(v.max()), float(v.max() / v.min())


def render(viab_df, nominal_df, lamp_df, aop_df, cross, arms, km_plausible, km_probe,
           model_version):
    L = []
    A = L.append

    A("# Lysosomal-load → injury calibration: f(C_ly) from Jarzina (2022)")
    A("")
    A(f"Generated by `injury_calibration/run_calibration.py` against the frozen "
      f"**{model_version}** accumulation model (`model_core_v04.py`). "
      f"Numbers below are computed, not transcribed.")
    A("")

    # ---- Lead caveat (required) -------------------------------------------
    A("## Read this first")
    A("")
    A("**C_ly50 is K_m-conditional, and K_m is not identifiable from the accumulation "
      "model's calibration.** That calibration used a single dose (34 µM); the injury "
      "data sits at 15.6–1000 µM. Uptake saturation across that range is governed by "
      "K_m, which no single-dose experiment can constrain. Every C_ly50 below is "
      "therefore reported as a band across a K_m sweep, never as a point estimate.")
    A("")
    A("Two structural caveats on the numbers themselves:")
    A("")
    A("- **The K_m dependence is very uneven between arms.** RPTEC's entire viability "
      "transition (91% → 5.8%) sits at 31–125 µM, within ~4× of the 34 µM calibration "
      "dose, so its C_ly is nearly pinned by the calibration. NRK's transition sits at "
      "250–1000 µM, deep in the extrapolated saturating regime. C_ly50(NRK) is thus far "
      "more K_m-sensitive than C_ly50(RPTEC), and it is the load-bearing number in the "
      "collapse test below.")
    A("- **The two arms use different floor conventions.** RPTEC's viability data reaches "
      "zero (0.8, 0.0, 0.0 % at 250/500/1000 µM), so its Hill fixes bottom = 0. NRK's "
      "lowest observed viability is 23% at the highest dose tested, so its Hill frees the "
      "floor into [0, 20] rather than extrapolating below every observation. Because a "
      "free floor moves the Hill midpoint off 50% viability, all cross-arm comparisons "
      "use **`C_ly50_abs`** — the load at 50% *absolute* viability, in closed form from "
      "the fit — which is the same physical quantity in both arms. `C_ly50_hill` (the raw "
      "fitted parameter) is reported alongside for transparency.")
    A("")

    # Did the free floor actually engage? Reported because freeing it was a deliberate
    # decision, and the honest outcome is that the data did not use the freedom.
    if "bottom_collapsed_to_zero" in viab_df.columns:
        fb = viab_df[viab_df.get("free_bottom", False) == True]  # noqa: E712
        if len(fb):
            n_zero = int(fb["bottom_collapsed_to_zero"].sum())
            if n_zero == len(fb):
                A("> **Note on the NRK free floor:** it was freed in case NRK's unreached "
                  "floor biased the fit, but the optimiser drove it to **0 at every K_m** "
                  "— the data provide no evidence for a non-zero floor, and a plain "
                  "top-100/bottom-0 Hill reproduces NRK's 23%-at-1000 µM point without "
                  "one. The freedom was therefore unused, and `C_ly50_hill` equals "
                  "`C_ly50_abs` throughout. The precaution cost nothing and its outcome "
                  "is itself informative: the NRK C_ly50 is not inflated by an assumed "
                  "floor.")
            else:
                A(f"> **Note on the NRK free floor:** it engaged (non-zero) in "
                  f"{len(fb) - n_zero}/{len(fb)} fits, so `C_ly50_hill` and "
                  f"`C_ly50_abs` differ for those rows. Compare the two columns below.")
            A("")

    # ---- Headline bands ----------------------------------------------------
    A("## 1. The C_ly50 band")
    A("")
    A("Load at 50% absolute viability, in nM, across the K_m sweep. "
      f"K_m ∈ {{{', '.join(str(int(k)) for k in km_plausible)}}} µM is the "
      f"**physiologically plausible subset** (matching `concentration_sweep_mm_v04.py` "
      f"and prior work). K_m ∈ {{{', '.join(str(int(k)) for k in km_probe)}}} µM are "
      "**limiting-behaviour probes, not equally-weighted candidates**: once K_m greatly "
      "exceeds the dose range, uptake becomes effectively linear and C_ly-indexing "
      "collapses back toward plain nominal-dose indexing, and a K_m of 2000 µM implies "
      "implausibly weak polymyxin–megalin binding. The reported band should not be read "
      "as four-orders-unconstrained.")
    A("")

    for cell in ["RPTEC", "NRK"]:
        lo_p, hi_p, fold_p = _band(viab_df, cell, km_subset=km_plausible)
        lo_a, hi_a, fold_a = _band(viab_df, cell)
        if lo_p is None:
            continue
        A(f"- **{cell}** — plausible subset: {_fmt(lo_p)}–{_fmt(hi_p)} nM "
          f"({fold_p:.2f}× spread). Full sweep incl. probes: {_fmt(lo_a)}–{_fmt(hi_a)} nM "
          f"({fold_a:.2f}×).")
    A("")

    cols = ["K_m", "K_m_class", "cell_line", "C_ly50_abs", "C_ly50_hill", "n", "bottom",
            "ci_boot_lo", "ci_boot_hi", "ci_cov_lo", "ci_cov_hi", "sat_decades",
            "ratio_NRK_over_RPTEC"]
    have = [c for c in cols if c in viab_df.columns]
    A("| " + " | ".join(have) + " |")
    A("|" + "|".join(["---"] * len(have)) + "|")
    for _, r in viab_df.sort_values(["K_m", "cell_line"]).iterrows():
        cells = []
        for c in have:
            v = r[c]
            if c in ("K_m_class", "cell_line"):
                cells.append(str(v))
            elif c in ("n", "bottom", "sat_decades", "ratio_NRK_over_RPTEC"):
                cells.append(_fmt(v, 2))
            else:
                cells.append(_fmt(v))
        A("| " + " | ".join(cells) + " |")
    A("")
    A("Full table: `results/cly50_by_km.csv`. Figure: `figures/injury/cly50_vs_km_band.png`.")
    A("")

    # ---- CI method disagreement -------------------------------------------
    A("### Confidence intervals: two methods, deliberately")
    A("")
    A("Both an asymptotic CI (from the fit covariance) and a nonparametric residual "
      "bootstrap CI are reported, because with 4–6 points per arm neither alone is "
      "trustworthy. **Where the two disagree substantially, read that as evidence the "
      "fit is poorly constrained** — not as licence to quote the narrower number.")
    A("")
    if {"ci_cov_lo", "ci_boot_lo"} <= set(viab_df.columns):
        w = viab_df.dropna(subset=["ci_cov_lo", "ci_cov_hi", "ci_boot_lo", "ci_boot_hi"]).copy()
        if not w.empty:
            w["cov_w"] = w["ci_cov_hi"] - w["ci_cov_lo"]
            w["boot_w"] = w["ci_boot_hi"] - w["ci_boot_lo"]
            w = w[w["cov_w"] > 0]
            if not w.empty:
                r = w["boot_w"] / w["cov_w"]
                A(f"Across the sweep the bootstrap interval is {r.min():.1f}×–{r.max():.1f}× "
                  f"the width of the covariance interval (median {r.median():.1f}×).")
                A("")
                if r.median() < 1.0:
                    A("**The bootstrap comes out _narrower_ than the asymptotic interval, "
                      "and that is a warning rather than a reassurance.** A residual "
                      "bootstrap conditions on the fitted curve and resamples only the "
                      "scatter around it; because these Hill fits track the digitised "
                      "points closely, that scatter is small, so the interval it produces "
                      "is narrow almost by construction. It propagates neither uncertainty "
                      "in the functional form nor error in the hand-digitisation — and, "
                      "critically, neither interval propagates K_m. **Both CIs are "
                      "therefore conditional on a given K_m and both are far narrower "
                      "than the real uncertainty on C_ly50, which is dominated by the K_m "
                      "band in §1.** Quote the band, not the CI.")
                else:
                    A("The bootstrap is the wider of the two, consistent with the "
                      "asymptotic interval being optimistic at this n. Note that neither "
                      "interval propagates K_m, so both remain conditional on it and the "
                      "K_m band in §1 dominates either.")
                A("")

    # ---- Collapse test -----------------------------------------------------
    A("## 2. Does the human/rat sensitivity gap collapse on the C_ly axis?")
    A("")
    A("Jarzina's nominal EC50s differ ~10× between species (~57 µM human vs ~575 µM rat), "
      "which they attribute to uptake. If C_ly is genuinely the cell-intrinsic injury "
      "variable, mapping each line through its **own** k_uptake should bring the two "
      "C_ly50 values together — ratio ≈ 1.")
    A("")
    if "ratio_NRK_over_RPTEC" in viab_df.columns:
        rr = viab_df.drop_duplicates("K_m").sort_values("K_m")
        rr = rr[np.isfinite(rr["ratio_NRK_over_RPTEC"])]
        if not rr.empty:
            A("| K_m (µM) | class | ratio NRK / RPTEC |")
            A("|---|---|---|")
            for _, r in rr.iterrows():
                A(f"| {_fmt(r['K_m'])} | {r['K_m_class']} | "
                  f"{_fmt(r['ratio_NRK_over_RPTEC'], 2)} |")
            A("")
            A(f"**The ratio is itself strongly K_m-dependent** "
              f"({rr['ratio_NRK_over_RPTEC'].min():.2f} → "
              f"{rr['ratio_NRK_over_RPTEC'].max():.2f} across the sweep). The collapse "
              "test therefore cannot return a K_m-independent verdict: the unidentified "
              "parameter controls the answer. This is the central finding, and it inverts "
              "the logic usefully — *if* one accepts C_ly as a cell-intrinsic injury "
              "threshold, the data becomes an argument about which K_m is consistent with "
              "that premise.")
            A("")

    A("### Primary result: the crossing K_m")
    A("")
    if np.isfinite(cross.get("K_m_cross", np.nan)):
        lo, hi = cross["ci"]
        A(f"Solving C_ly50(NRK) = C_ly50(RPTEC) gives a crossing at")
        A("")
        A(f"> **K_m = {_fmt(cross['K_m_cross'])} µM**"
          + (f"  (bootstrap 95% CI {_fmt(lo)}–{_fmt(hi)} µM"
             + (f", CV {cross['cv']:.2f}" if np.isfinite(cross.get("cv", np.nan)) else "")
             + ")" if np.isfinite(lo) else "  (bootstrap CI unavailable)"))
        A("")
        A("This is the lysosomal K_m the collapse test implies: the value at which the "
          "human/rat sensitivity gap is *fully* explained by differential uptake, with no "
          "residual species difference in intrinsic lysosomal tolerance. It is more "
          "informative than any single grid point, and the swept grid is best read as the "
          "visualisation around it.")
        A("")
        in_plaus = min(km_plausible) <= cross["K_m_cross"] <= max(km_plausible)
        if in_plaus:
            A("The crossing falls **inside the physiologically plausible K_m subset**, "
              "which is genuine support for the C_ly-indexing premise: there exists a "
              "credible K_m at which C_ly behaves as a species-invariant injury threshold.")
        else:
            A(f"⚠️ The crossing falls **outside the plausible subset** "
              f"({min(km_plausible):.0f}–{max(km_plausible):.0f} µM), in the "
              "limiting-probe region. Read this as a genuine negative result: within "
              "credible K_m values the gap does *not* fully close, so either the "
              "species difference is not purely uptake-driven, or the accumulation "
              "model's uptake calibration does not capture all of it. Do not quietly "
              "adopt the crossing K_m as an estimate of the real K_m — it is the value "
              "that *would* be required, and it is implausibly high.")
        A("")
    else:
        A("The ratio does not cross 1 anywhere in the swept K_m range, so no crossing K_m "
          "exists. The human/rat C_ly50 gap does not close under any K_m considered — a "
          "substantive negative result for the C_ly-indexing premise.")
        A("")
    A("Figure: `figures/injury/cly50_ratio_crossing.png`.")
    A("")

    # ---- AOP ordering ------------------------------------------------------
    A("## 3. AOP ordering on the C_ly axis (KE1 before KE3)")
    A("")
    if aop_df is None or len(aop_df) == 0:
        A("No LAMP arms available — ordering check not run.")
    else:
        n_ok = int(aop_df["aop_ok"].sum())
        n_tot = int(len(aop_df))
        verdict = "PASS" if n_ok == n_tot else ("PARTIAL" if n_ok else "FAIL")
        A(f"Lysosomal disturbance (KE1, LAMP-1 crossing 2× control) should occur at a "
          f"**lower** lysosomal load than cell death (KE3, C_ly50). "
          f"**{verdict}** — {n_ok}/{n_tot} (K_m × cell line) combinations satisfy the "
          f"ordering.")
        A("")
        A("| K_m (µM) | cell line | KE1 onset C_ly (nM) | KE3 C_ly50 (nM) | ordering |")
        A("|---|---|---|---|---|")
        for _, r in aop_df.sort_values(["K_m", "cell_line"]).iterrows():
            A(f"| {_fmt(r['K_m'])} | {r['cell_line']} | {_fmt(r['lamp_onset_cly'])} | "
              f"{_fmt(r['C_ly50_abs'])} | {'✅ pass' if r['aop_ok'] else '❌ fail'} |")
        A("")
        A("The LAMP fit uses a free-top monotonic form (LAMP exceeds 1000% of control with "
          "no plateau in range, so the fixed-asymptote Hill is inapplicable). Its "
          "functional form is deliberately not over-invested in — this arm exists for the "
          "ordering check only, not as a quantitative injury function. The NRK LAMP arm "
          "has no usable SDs and is fitted unweighted.")
        A("")
        if lamp_df is not None and "onset_spread" in lamp_df.columns:
            sp = lamp_df["onset_spread"].dropna()
            nb = int(lamp_df["A_at_bound"].sum()) if "A_at_bound" in lamp_df else 0
            if len(sp):
                A(f"**The LAMP plateau is unidentified** — with no upper asymptote in "
                  f"range it runs to its bound in {nb}/{len(lamp_df)} fits, so the fitted "
                  f"plateau is meaningless and is not reported as a result. The *onset*, "
                  f"however, is well determined: refitting under plateau bounds of 1 500 / "
                  f"5 000 / 20 000 % moves it by only "
                  f"{sp.min():.2f}×–{sp.max():.2f}×. The ordering column below uses the "
                  f"worst-case onset across those refits, so a 'robust' verdict means the "
                  f"ordering holds regardless of that arbitrary bound.")
                A("")
        if "aop_robust" in aop_df.columns:
            n_rob = int(aop_df["aop_robust"].sum())
            A(f"Robustness: {n_rob}/{n_tot} combinations keep the ordering even at the "
              f"worst-case onset.")
    A("")
    A("Figure: `figures/injury/lamp_vs_cly.png`.")
    A("")

    # ---- Saturation --------------------------------------------------------
    A("## 4. Saturation / identifiability diagnostic")
    A("")
    A("If C_ly plateaus across the concentrations where viability is still falling, then "
      "several data points collapse onto near-identical lysosomal loads with very "
      "different viabilities — C_ly50 is then poorly identified from the top of the "
      "curve, and it is evidence that **non-lysosomal mechanisms** (mitochondrial, "
      "membrane) contribute to killing at high dose. The metric below is the number of "
      "decades of C_ly spanned by the viability transition.")
    A("")
    if "sat_decades" in viab_df.columns:
        s = viab_df.dropna(subset=["sat_decades"])
        fired = s[s["sat_decades"] < 0.5]
        A("| K_m (µM) | cell line | transition span (decades of C_ly) | flag |")
        A("|---|---|---|---|")
        for _, r in s.sort_values(["K_m", "cell_line"]).iterrows():
            flag = "⚠️ saturated" if r["sat_decades"] < 0.5 else "ok"
            A(f"| {_fmt(r['K_m'])} | {r['cell_line']} | {_fmt(r['sat_decades'], 2)} | {flag} |")
        A("")
        if len(fired):
            worst = fired.sort_values("sat_decades").iloc[0]
            A(f"**The diagnostic fires** in {len(fired)}/{len(s)} combinations, worst at "
              f"K_m = {_fmt(worst['K_m'])} µM / {worst['cell_line']} "
              f"({_fmt(worst['sat_decades'], 2)} decades). As expected this is worst at "
              "low K_m, where uptake saturates hardest.")
        else:
            A("The diagnostic does not fire: the viability transition spans an adequate "
              "range of C_ly at every K_m considered.")
    A("")
    A("A related flag: the fitted Hill coefficient `n`. Where C_ly saturates across the "
      "transition the curve is near-vertical on the C_ly axis and `n` runs to its bound "
      f"(max {50.0:.0f}). Any `n` above 10 in the table is a saturation artefact and must "
      "not be read as a cooperativity estimate.")
    if "n_saturation_flag" in viab_df.columns:
        nf = int(viab_df["n_saturation_flag"].sum())
        A(f" Currently {nf}/{len(viab_df)} fits are so flagged.")
    A("")
    A("Figure: `figures/injury/saturation_diagnostic.png`.")
    A("")

    # ---- Control fit -------------------------------------------------------
    A("## 5. Control: the same fit on the nominal axis")
    A("")
    A("A machinery check, not part of the spec: fitting the identical Hill against "
      "**nominal concentration** should recover Jarzina's published EC50s (~57 µM RPTEC, "
      "~575 µM NRK). If it does, the fitting code is sound and its output on the C_ly "
      "axis can be trusted.")
    A("")
    if nominal_df is not None and len(nominal_df):
        A("| cell line | EC50 (µM, 50% absolute) | n | floor | Jarzina reported |")
        A("|---|---|---|---|---|")
        ref = {"RPTEC": "~57 µM", "NRK": "~575 µM"}
        for _, r in nominal_df.iterrows():
            A(f"| {r['cell_line']} | {_fmt(r['EC50_abs_uM'], 1)} | {_fmt(r['n'], 2)} | "
              f"{_fmt(r['bottom'], 1)} | {ref.get(r['cell_line'], '—')} |")
        A("")

    # ---- Provenance --------------------------------------------------------
    A("## Provenance and scope")
    A("")
    A(f"- **Accumulation model:** `model_core_v04.py` ({model_version}), imported "
      "unmodified. Uptake anchoring `V_max = k_uptake · (K_m + 34)` keeps the 34 µM "
      "calibration exact at every K_m. C_ly is emitted in nM; C_ext is in µM.")
    A("- **Exposure protocol:** constant C_ext for 24 h, matching Jarzina's single-timepoint "
      "readouts. The C_ly summary statistic is swappable (`at_24h` default, `peak` and "
      "`auc` available); results here use the 24 h instantaneous value.")
    A("- **Per-line uptake:** RPTEC uses `k_uptake_RPTEC`, NRK uses `k_uptake_NRK` "
      "(Step 2A, k_deg shared). The alternative NRK Step 2B fit (k_deg free) rescales "
      "C_ly by a near-constant ~1.12× at every dose and K_m, so it shifts C_ly50(NRK) "
      "~12% and does not change any verdict above.")
    A("- **Regression guard:** RPTEC total intracellular at 34 µM / 24 h is asserted "
      "against the frozen value. This pins *total*, not C_ly — C_ly was never measured "
      "(Jarzina assayed total by LC-MS/MS), so a C_ly guard would only pin the model to "
      "itself.")
    A("- **Data:** hand-digitised from Jarzina Fig. 5, provisional. Cathepsin D (KE2, "
      "Fig 5C) is deliberately excluded — Jarzina themselves flag it as responding out of "
      "AOP order and question its reliability as a KE2 marker. Only discrete measured "
      "points are used; Jarzina's own fitted curves are never fitted to.")
    A("- **Known limitation:** RPTEC has no measured point between 91% and 40% viability, "
      "so its midpoint is interpolated across a single 2× dose step. This is stated rather "
      "than patched — adding free parameters to 6 points would manufacture precision.")
    A("- **Out of scope:** coupling f(C_ly) into a Gebremichael-style population injury "
      "model. This task produces and characterises f(C_ly) only.")
    A("")
    return "\n".join(L) + "\n"
